[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/child-safety"
  to = "/child-safety.html"
  status = 200

[[redirects]]
  from = "/creators"
  to = "/creators.html"
  status = 200

[[redirects]]
  from = "/events"
  to = "/events.html"
  status = 200
